spring.application.name=SecureTaskManagement


spring.datasource.url=jdbc:mysql://localhost:3306/secure_task_management
spring.datasource.username=root
spring.datasource.password=8941

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true